# 行列の導入

## 学ぶこと

- NumPy配列の結合：concatenate, stack
- NumPy配列のshapeとaxis, 集約関数
- 行列積の導入

## 配列の結合

### concatenate

In [5]:
a = [1, 2, 3]
b = [100, 101, 102]
a + b

[1, 2, 3, 100, 101, 102]

In [6]:
a.append(b)
a

[1, 2, 3, [100, 101, 102]]

In [11]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([100, 101, 102])

# numpyでは関数を使う
np.concatenate([x, y])

array([  1,   2,   3, 100, 101, 102])

In [12]:
np.concatenate([x, x, y])

array([  1,   2,   3,   1,   2,   3, 100, 101, 102])

In [14]:
np.concatenate([x] * 4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
np.array([x] * 4)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### ベストプラクティス

appendを使ってリストにためてからnp.arrayを適用するのと，np.concatenateでNumpy配列を結合するのではどちらが早いのだろうか?

In [22]:
from mypy.mymodule import TimeExecute

chunk_size = 100
def pattern1():
    x = []
    for i in range(10000):
        for j in range(chunk_size):
            x.append(j)
    x= np.array(x)

def pattern2():
    x = []
    for i in range(10000):
        x += list(range(chunk_size))
    x = np.array(x)

def pattern3():
    x = []
    for i in range(10000):
        x.append(np.arange(chunk_size))
    x = np.concatenate(x)

def pattern4():
    x = np.array([])
    for i in range(10000):
        x = np.concatenate([x, np.arange(chunk_size)])

In [23]:
with TimeExecute():
    pattern1()

117.689 [msec]


In [24]:
with TimeExecute():
    pattern2()

80.784 [msec]


In [25]:
with TimeExecute():
    pattern3()

16.984 [msec]


In [26]:
with TimeExecute():
    pattern4()

12,685.144 [msec]


基本的にはpattern3, つまりNumPy配列をリストに入れる作業の後に，
まとめて結合させるのが良い．
chunk_sizeが小さい場合には他のpatternが優勢なときもある. 

配列は要素の結合などのように素数が変化する処理には向いていないため，
結合回数を少なくすることがよい. 


## NumPy配列の分割


### スライス

普通に働くので省略.

### np.split

あまり使う機会はあにが指定した数に要素を当分する. 

In [28]:
x    = np.arange(8)
a, b = np.split(x, 2)
print(a)
print(b)

[0 1 2 3]
[4 5 6 7]


## 多次元リストと多次元配列

In [34]:
x = np.array([np.arange(1, 4)] * 4) + np.array(np.arange(4) * 10).reshape(4, 1)
x

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [35]:
# 1行目
x[0]

array([1, 2, 3])

In [36]:
# 1列目
x[:, 0]

array([ 1, 11, 21, 31])

In [48]:
# 1要素
x[0,0], x[0][0]

(1, 1)

In [49]:
# 1要素を配列で
x[0, 0:1]

array([1])

### 行列の積み上げ

np.concatenateは末尾への結合であったが，np.stackは配列を積み重ねていくことが可能である. 


In [45]:
x1 = np.arange(3)
x2 = 3 + np.arange(3)
np.concatenate([x1, x2])

array([0, 1, 2, 3, 4, 5])

In [46]:
np.stack([x1, x2])

array([[0, 1, 2],
       [3, 4, 5]])

## 多次元配列のスライスの解釈

In [50]:
anko_sell = np.array([[100, 50, 50], [50, 30, 100],[50, 50, 70], [100, 50, 100]])
anko_sell

array([[100,  50,  50],
       [ 50,  30, 100],
       [ 50,  50,  70],
       [100,  50, 100]])

In [51]:
anko_sell[0, ]

array([100,  50,  50])

In [53]:
anko_sell[:, 0]

array([100,  50,  50, 100])

In [59]:
anko_sell[::2, ::]

array([[100,  50,  50],
       [ 50,  50,  70]])

### 行と列が反転したときのスライス

In [56]:
annko_vertical = anko_sell.T
annko_vertical

array([[100,  50,  50, 100],
       [ 50,  30,  50,  50],
       [ 50, 100,  70, 100]])

### スライスと識別子

スライスしたときに作成されるのは元の変数のViewである．

スライスで作ったViewと元の変数は識別しが異なる，ということになる.

ただし配列を抜けるとそれは数値になるので，そこでも識別子は異なる. 


In [60]:
x = np.arange(5)
print(id(x[::]))
print(id(x[:]))
print(id(x))


1746670396160
1746670396160
1746670397920


In [61]:
x = np.array([[1, 2, 3], [11, 12, 13], [21, 22, 23]])
print(id(x[1,::]))
print(id(x[1,:]))
print(id(x[1,1]))
print(id(x[1]))

1746673298768
1746673295888
1746671301968
1746673295888


## NumPy配列のshape

In [62]:
x = np.arange(5)
print(x.shape)
print(len(x))

(5,)
5


In [64]:
x = np.array([[1,2], [3,4], [5,6]])
print(x.shape)
print(len(x))

(3, 2)
3


## 集約関数


In [68]:
x = np.array([16, 12, 12, 11, 11])
print(np.sum(x)) # 62
print(np.prod(x)) # 278784p
ｐrint(np.mean(x)) # 12.4
print(np.std(x)) # 1.8547236990991407
print(np.median(x)) # 12.0
print(len(x)) # 5
print(np.max(x)) # 16
print(np.min(x)) # 11
print(np.argmax(x)) 
print(np.argmin(x))

62
278784
12.4
1.8547236990991407
12.0
5
16
11
0
3


集約関数ではないが，いわゆる最大値の管理，最小値の管理とう面で活用出来るのがnp.maxmium/minimumである．これらの関数はnp.clipと等価である. 

In [69]:
x = np.arange(10)
print(np.maximum(np.minimum(x, 7), 3)) # [3 3 3 3 4 5 6 7 7 7]
print(np.minimum(np.maximum(x, 3), 7))

[3 3 3 3 4 5 6 7 7 7]
[3 3 3 3 4 5 6 7 7 7]


In [70]:
np.clip(x, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

## 多次元配列と集約関数のaxis

In [71]:
anko_sell = np.array(
    [[100, 50, 50], [50, 30, 100],[50, 50, 70], [100, 50, 100]])
print(np.sum(anko_sell)) 

800


In [73]:
# 月単位
print("月単位", np.sum(anko_sell, axis = 1))

月単位 [200 180 170 250]


In [74]:
# 商品単位
print("商品単位", np.sum(anko_sell, axis = 0))


商品単位 [300 180 320]


## 多次元配列の次元

numpy配列の次元とは`len(x.shape)`である.


## 多次元配列化出来ない「リストのリスト」

リストのリストは通常，NumPyヘア塚しても多次元配列にはならないが，入れ子になった内側のリストの要素数が全て同じ，つまり多次元リストに限定すれば多次元配列となる. 

とはいえ，下記とおり思わぬエラーが発生するもとであるので，基本的にはリストのリストか直接多次元配列を作成することはやめておいた方が良い. 


In [76]:
x = [[1, 2], [3, 4, 5], [6, 7, 8, 9]]
print(x)
x = np.array(x)
print(x) # エラーにはならないが、多次元配列ではない
print(x.dtype) # object型になる
print(x.shape) # あたかも1次元配列のようにみなされる
print(x[:, 1]) # これはエラー

[[1, 2], [3, 4, 5], [6, 7, 8, 9]]
[list([1, 2]) list([3, 4, 5]) list([6, 7, 8, 9])]
object
(3,)


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

## 配列の結合でのaxis